Twitter clone
DejazmachMolla/Twittter pull request #1
Opened 2021-02-04 15:39 UTC by DejazmachMolla

Created a clone of Twitter to practice Authentication and Authorization using devise. The project

- [ ] enables registration, log in and logout of users

- [ ] allows edit and delete of tweeets only for authorized users

2021-02-04 22:05 UTC, LamiaSristy requested changes
# Status: Change Required. ♻️

Hello @ 🙌

Great work so far. You have used `devise`gem for authentication correctly. 👏 👏 👏

You need to implement the works below to get the project approved!🛠️

Please check my points here: 👇

`[REQUIRED]`

- [x] As a guest you can see only the post's text, not the username of the author.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
![ss1](https://user-images.githubusercontent.com/56501603/106960878-0f29dd80-673d-11eb-81ff-e0b4db781170.png)

- [ ] In `routes.rb` file, It creates the application routes using `resources :posts, only: [:new, :create, :index]` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
In your case it should be `resources :tweeets, only: [:new, :create, :index]`

- [ ] In `tweeets_controller.rb`, the `new` method initializes an empty post `@post = Post.new` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))In your case it should be ` @tweeet = Tweeet.new` 

- [ ] In `tweeets_controller.rb`, the `index` method doesn't needs `@tweeet = Tweeet.new`.


Please make the changes and ask for a re-review.

Feel free to reach me at @lamiasristy 🙋

2021-02-04 22:07 UTC, LamiaSristy commented on config/routes.rb
>    resources :tweeets
It creates the application routes using :  `resources :tweeets, only: [:new, :create, :index]` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

2021-02-04 22:08 UTC, LamiaSristy commented on app/controllers/tweeets_controller.rb
> +    @tweeet = Tweeet.new
Remove  `@tweeet = Tweeet.new`

2021-02-04 22:08 UTC, LamiaSristy commented on app/controllers/tweeets_controller.rb
>    end
` @tweeet = Tweeet.new`

2021-02-05 08:50 UTC, DejazmachMolla commented on app/controllers/tweeets_controller.rb
> +    @tweeet = Tweeet.new
Thanks, but I think this is necessary to enable creation of new tweet on the index page. Had the new tweet page was separate from the index page, it wouldn't have been needed as you said.

2021-02-05 11:46 UTC, mimipeshy commented
### STATUS: APPROVED 🥳 🍾 

Hey there @DejazmachMolla and @LamiaSristy  :wave: :wave: good job on working on the requested changes. This project is therefore approved. Go ahead and merge. All the best in the next milestones :man_technologist: 

Regards
Peris Ndanu

2021-02-05 11:56 UTC, merged